"""Word document export utility using python-docx"""
from datetime import datetime
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from typing import List, Dict


def create_docx_export(
    document_name: str,
    qa_history: List[Dict],
    output_path: str
) -> str:
    """
    Create a Word document export of document Q&A history.
    
    Args:
        document_name: Name of the document
        qa_history: List of Q&A dictionaries with 'question', 'answer', 'created_at'
        output_path: Path to save the DOCX file
        
    Returns:
        Path to created DOCX file
    """
    # Create document
    doc = Document()
    
    # Set document margins
    sections = doc.sections
    for section in sections:
        section.top_margin = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin = Inches(1)
        section.right_margin = Inches(1)
    
    # Title
    title = doc.add_heading('Document Analysis Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title_run = title.runs[0]
    title_run.font.color.rgb = RGBColor(44, 62, 80)
    
    # Document info
    doc.add_paragraph()
    
    info_para = doc.add_paragraph()
    info_para.add_run('Document: ').bold = True
    info_para.add_run(document_name)
    
    date_para = doc.add_paragraph()
    date_para.add_run('Generated: ').bold = True
    date_para.add_run(datetime.now().strftime('%B %d, %Y at %I:%M %p'))
    
    qa_count_para = doc.add_paragraph()
    qa_count_para.add_run('Total Q&A: ').bold = True
    qa_count_para.add_run(str(len(qa_history)))
    
    doc.add_paragraph()
    
    # Q&A Section heading
    qa_heading = doc.add_heading('Questions & Answers', level=1)
    qa_heading_run = qa_heading.runs[0]
    qa_heading_run.font.color.rgb = RGBColor(52, 152, 219)
    
    # Add each Q&A
    for idx, qa in enumerate(qa_history, 1):
        # Q&A number
        number_para = doc.add_paragraph()
        number_run = number_para.add_run(f'Q&A #{idx}')
        number_run.font.size = Pt(10)
        number_run.font.color.rgb = RGBColor(127, 140, 141)
        number_run.bold = True
        
        # Question
        question_para = doc.add_paragraph()
        question_para.paragraph_format.left_indent = Inches(0.3)
        q_label = question_para.add_run('Q: ')
        q_label.bold = True
        q_label.font.color.rgb = RGBColor(44, 62, 80)
        question_text = question_para.add_run(qa.get('question', 'N/A'))
        question_text.font.size = Pt(11)
        
        # Answer
        answer_para = doc.add_paragraph()
        answer_para.paragraph_format.left_indent = Inches(0.3)
        answer_para.paragraph_format.right_indent = Inches(0.3)
        a_label = answer_para.add_run('A: ')
        a_label.bold = True
        a_label.font.color.rgb = RGBColor(44, 62, 80)
        answer_text = answer_para.add_run(qa.get('answer', 'N/A'))
        answer_text.font.size = Pt(11)
        answer_text.font.color.rgb = RGBColor(52, 73, 94)
        
        # Timestamp
        if 'created_at' in qa:
            timestamp = datetime.fromisoformat(str(qa['created_at']).replace('Z', '+00:00'))
            timestamp_para = doc.add_paragraph()
            timestamp_para.paragraph_format.left_indent = Inches(0.3)
            timestamp_run = timestamp_para.add_run(
                f'Asked on {timestamp.strftime("%B %d, %Y at %I:%M %p")}'
            )
            timestamp_run.italic = True
            timestamp_run.font.size = Pt(9)
            timestamp_run.font.color.rgb = RGBColor(127, 140, 141)
        
        # Add spacing
        doc.add_paragraph()
    
    # Footer
    doc.add_paragraph()
    footer_para = doc.add_paragraph()
    footer_run = footer_para.add_run(
        'Generated by Finalytics - AI-Powered Financial Analytics Platform'
    )
    footer_run.italic = True
    footer_run.font.size = Pt(9)
    footer_run.font.color.rgb = RGBColor(127, 140, 141)
    footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save document
    doc.save(output_path)
    
    return output_path

