"""Email sending utility using Gmail SMTP"""
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from pathlib import Path
from typing import Optional
from app.config import settings


def send_email(
    to_email: str,
    subject: str,
    body: str,
    attachment_path: Optional[str] = None
) -> bool:
    """
    Send email via Gmail SMTP.
    
    Args:
        to_email: Recipient email address
        subject: Email subject
        body: Email body (HTML supported)
        attachment_path: Optional path to file attachment
        
    Returns:
        True if sent successfully, False otherwise
    """
    # Check if SMTP is configured
    if not settings.SMTP_USERNAME or not settings.SMTP_PASSWORD:
        raise ValueError(
            "Email not configured. Please set SMTP_USERNAME and SMTP_PASSWORD in .env"
        )
    
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = settings.SMTP_FROM_EMAIL or settings.SMTP_USERNAME
        msg['To'] = to_email
        msg['Subject'] = subject
        
        # Add body
        msg.attach(MIMEText(body, 'html'))
        
        # Add attachment if provided
        if attachment_path:
            attachment_path_obj = Path(attachment_path)
            if attachment_path_obj.exists():
                with open(attachment_path, 'rb') as file:
                    part = MIMEApplication(file.read(), Name=attachment_path_obj.name)
                    part['Content-Disposition'] = f'attachment; filename="{attachment_path_obj.name}"'
                    msg.attach(part)
        
        # Connect to Gmail SMTP server
        with smtplib.SMTP(settings.SMTP_HOST, settings.SMTP_PORT) as server:
            server.starttls()
            server.login(settings.SMTP_USERNAME, settings.SMTP_PASSWORD)
            server.send_message(msg)
        
        return True
        
    except Exception as e:
        print(f"Error sending email: {e}")
        return False


def create_analysis_email_body(document_name: str, qa_count: int) -> str:
    """
    Create HTML email body for document analysis export.
    
    Args:
        document_name: Name of the document
        qa_count: Number of Q&A pairs
        
    Returns:
        HTML email body
    """
    return f"""
    <html>
        <head>
            <style>
                body {{
                    font-family: Arial, sans-serif;
                    line-height: 1.6;
                    color: #333;
                }}
                .header {{
                    background-color: #3498db;
                    color: white;
                    padding: 20px;
                    text-align: center;
                }}
                .content {{
                    padding: 20px;
                }}
                .info {{
                    background-color: #f8f9fa;
                    padding: 15px;
                    border-left: 4px solid #3498db;
                    margin: 20px 0;
                }}
                .footer {{
                    text-align: center;
                    padding: 20px;
                    color: #7f8c8d;
                    font-size: 12px;
                }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📊 Document Analysis Report</h1>
            </div>
            <div class="content">
                <p>Hello,</p>
                <p>Your document analysis report is ready! Please find the attached report with all your questions and AI-generated answers.</p>
                
                <div class="info">
                    <p><strong>Document:</strong> {document_name}</p>
                    <p><strong>Total Q&A Pairs:</strong> {qa_count}</p>
                </div>
                
                <p>The attached report contains:</p>
                <ul>
                    <li>All your questions about the document</li>
                    <li>AI-generated answers based on document content</li>
                    <li>Timestamps for each interaction</li>
                </ul>
                
                <p>Thank you for using Finalytics!</p>
            </div>
            <div class="footer">
                <p><em>Generated by Finalytics - AI-Powered Financial Analytics Platform</em></p>
                <p>This is an automated message. Please do not reply.</p>
            </div>
        </body>
    </html>
    """

