"""Add stock_comparisons table

Revision ID: 3c8473ad6100
Revises: e39a788999ca
Create Date: 2025-10-28 23:26:39.987163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8473ad6100'
down_revision = 'e39a788999ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_comparisons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker1', sa.String(length=10), nullable=False),
    sa.Column('ticker2', sa.String(length=10), nullable=False),
    sa.Column('comparison_data', sa.Text(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_comparisons_user_id'), 'stock_comparisons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_comparisons_user_id'), table_name='stock_comparisons')
    op.drop_table('stock_comparisons')
    # ### end Alembic commands ###

