"""Add stock_queries table

Revision ID: e39a788999ca
Revises: d5788b3f2e14
Create Date: 2025-10-28 23:21:59.569553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39a788999ca'
down_revision = 'd5788b3f2e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_queries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_queries_ticker'), 'stock_queries', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_queries_user_id'), 'stock_queries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_queries_user_id'), table_name='stock_queries')
    op.drop_index(op.f('ix_stock_queries_ticker'), table_name='stock_queries')
    op.drop_table('stock_queries')
    # ### end Alembic commands ###

